### ISSUE TITLE
rpds objects cannot be copied with deepcopy

### ISSUE THREAD

**Issue by eifinger** [crate-py/rpds#18]
I stumbled upon this issue due to [jsonschema](https://github.com/python-jsonschema/jsonschema) using this lib. I am not sure whether this issue belongs here.

When I execute this sample snippet:

```python
from copy import deepcopy
from rpds import HashTrieMap

m = HashTrieMap({"foo": "bar", "baz": "quux"})

c = deepcopy(m)

print(c)
```

I get the following stacktrace:

```console
python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    L2 = deepcopy(L)
  File "/Users/kevin.stillhammer/.rye/py/cpython@3.8.16/install/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'rpds.List' object
```

It would be great if this lib supports deepcopy.

**Comment by eifinger** [comment]
The issue originates from my use of [quart-openapi](https://github.com/factset/quart-openapi).

The [doc decorator](https://github.com/factset/quart-openapi/blob/master/quart_openapi/pint.py#L375) allows to decorate [quart](https://github.com/pallets/quart) routes:

```python
...
    @app.doc(tags=["Flow"], description="Create a todo item")
    @app.response(code=HTTPStatus.CREATED, description="Item created")
    async def post(self) -> Tuple[str, int]:
...
```

It is internaly using a jsonschema validator as objects and the merge function uses deepcopy internally:

https://github.com/factset/quart-openapi/blob/8e282355dbce22f844e2ed7b88e9db8e651d66ac/quart_openapi/utils.py#L89-L108

Given that the repos last commit nears its 2 year anniversary I will have to move to another maintained solution and will leave this here for others to find.

Thank you for the fast response! ❤️ 
I guess
