### ISSUE TITLE
ARM64 architecture error

### ISSUE THREAD

**Issue by prosyanoy** [crate-py/rpds#78]
Error when trying to launch jupyter on M1 Max chip:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyterlab/__init__.py", line 8, in <module>
    from .handlers.announcements import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyterlab/handlers/announcements.py", line 14, in <module>
    from jupyter_server.base.handlers import APIHandler
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_server/base/handlers.py", line 23, in <module>
    from jupyter_events import EventLogger
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_events/__init__.py", line 3, in <module>
    from .logger import EVENTS_METADATA_VERSION, EventLogger
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jupyter_events/logger.py", line 14, in <module>
    from jsonschema import ValidationError
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jsonschema/exceptions.py", line 15, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/referencing/__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/referencing/_core.py", line 9, in <module>
    from rpds import HashTrieMap, HashTrieSet, List
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rpds/__init__.py", line 1, in <module>
    from .rpds import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rpds/rpds.cpython-312-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rpds/rpds.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rpds/rpds.cpython-312-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rpds/rpds.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by Julian** [comment]
Hi there, please follow up with something that reproduces this strictly using this package.

**Comment by prosyanoy** [comment]
Idk how to reproduce it purely, isn't it obvious that the problem is in ARM64 chip support for the latest version of the package

**Comment by prosyanoy** [comment]
Maybe I wrong and it's jupyter somehow been based on this package recently

**Comment by Julian** [comment]
Nothing is particularly obvious unfortunately, I'm happy to look into things, but this would need to be minimized to confirm it's an issue here and not with either something downstream or your own setup. Please feel free to follow up if you do so.
